### ISSUE TITLE
[bug][responsive design] position of icons

### ISSUE THREAD

**Issue by robinmoussu** [pierrerousseau/quickmarks#1]
Hi. With a ~600px width screen (or a bit less), the up/down arrow, on the top right corner of the "bookmark a link" windows are misplaced (their are a bit too much on the right).

**Comment by pierrerousseau** [comment]
Thanks for the report !
There will be soon a full review of the design of the app, so I guess it will be solved at this time.

**Comment by pierrerousseau** [comment]
I don't know if you still use the app, but this bug does not apply with the new design!
