### ISSUE TITLE
Quickmarks keeps loading something….

### ISSUE THREAD

**Issue by nicofrand** [pierrerousseau/quickmarks#4]
With a brand new install, with or without any links saved, I keep having this "loading…":

![bug-quickmarks-loading](https://cloud.githubusercontent.com/assets/3419050/9563267/4180d3d4-4e7e-11e5-8f11-e651b863e944.png)

**Comment by pierrerousseau** [comment]
I don't know if you still use the app, but I think this bug does not exist any more with the new design.
