### ISSUE TITLE
Search raises errors if no bookmarks saved

### ISSUE THREAD

**Issue by nicofrand** [pierrerousseau/quickmarks#7]
Without any bookmarks saved, if I try to search for something (yes, there is no usecase to that),
some errors are raised in the console on the client side:

```js
Uncaught TypeError: Cannot read property 'values' of undefined
List.search @ list.js:240
```

**Comment by pierrerousseau** [comment]
Thanks for reporting this bugs and for the other issues that you did open. The UI of quickmarks will be reviewed in the coming weeks, I'll try to correct that at the same time.
